---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: node1
    image: '${MOLECULE_DISTRO:-geerlingguy/docker-centos7-ansible:latest}'
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: node2
    image: '${MOLECULE_DISTRO:-geerlingguy/docker-centos7-ansible:latest}'
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
scenario:
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
