---
- name: Prepare
  hosts: all
  tasks:
    - name: Install nginx on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - nginx
        update_cache: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
