---
- name: capturing cluster order constraint
  ansible.builtin.shell: |
    set -o pipefail
    pcs constraint order show --full | grep -E "(id:order-{{ _oder_filter }}-.+)"
  args:
    executable: /bin/bash
  vars:
    _oder_filter: >-
      {{ cluster_constraint.order.first_resource }}-{{ cluster_constraint.order.second_resource }}
  register: _pcs_order_constraint_show
  changed_when: false
  failed_when: false

- name: ensure cluster order constraint exists
  when: _pcs_order_constraint_show.rc != 0
  ansible.builtin.command: >
    pcs constraint order
      {{ cluster_constraint.order.first_resource_action }}
      {{ cluster_constraint.order.first_resource }}
      then
      {{ cluster_constraint.order.second_resource_action | default('') }}
      {{ cluster_constraint.order.second_resource }}
      {{ cluster_constraint.order.options | default([]) | join(' ') }}

- name: ensure cluster order constraint does not exists
  when:
    - cluster_constraint.order.state | default('present') | lower == 'absent'
    - _pcs_order_constraint_show.rc == 0
  ansible.builtin.command: >
    pcs constraint order remove
      {{ cluster_constraint.order.first_resource }}
      {{ cluster_constraint.order.second_resource }}
